// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "c9c7eec8-6e07-4cec-9dc8-56b944bb6cac");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1612279977);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1612279375);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1612279735);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1612279615);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1612279495);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1612279857);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1612279405);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1612280111);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 307200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1612279345);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ab077ce3-3adb-48c9-b06c-352c1f1dc81d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1612279402279");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1612281215279");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1612279359845");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1612300959845");
user_pref("browser.search.region", "HK");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1612279357");
user_pref("browser.slowStartup.averageTime", 11461);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1612279350);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1612279358299");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "97d1b2ba56bc414db18fcb4409afc219");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1612279978);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"6047d628-5170-46c9-9771-20a78a89a79b\",\"formautofill@mozilla.org\":\"9bb97744-f70b-4eda-85e4-fc55bfac0d19\",\"screenshots@mozilla.org\":\"e4dd56c4-bfbb-4c54-a4ea-9834aade8205\",\"webcompat-reporter@mozilla.org\":\"d2a2bd76-cab4-4965-9b40-74ba43d571f0\",\"webcompat@mozilla.org\":\"ea1c65cf-5da3-412d-b53c-fcc4bedf1f9b\",\"default-theme@mozilla.org\":\"a3dbc6c7-035b-4d8a-afa6-8d4ab7970018\",\"google@search.mozilla.org\":\"5bbd8666-c834-4e43-97b8-c31779811e4a\",\"amazondotcom@search.mozilla.org\":\"eb9335eb-2d53-454c-8124-5520db6121d4\",\"wikipedia@search.mozilla.org\":\"ce679bd0-c1a7-4b79-af77-21b5a2f64ea5\",\"bing@search.mozilla.org\":\"0362f5c5-ec8d-4e20-9260-1b6dcc819a96\",\"ddg@search.mozilla.org\":\"4f9b968f-9467-49da-8a69-ea8b4ae52973\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1612279502);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1612279500);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 76954);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1612279500);
user_pref("security.remote_settings.intermediates.checked", 1612279500);
user_pref("security.sandbox.content.tempDirSuffix", "a2f4f198-a286-479e-beb2-efc2f28b347d");
user_pref("security.sandbox.plugin.tempDirSuffix", "a8780230-7d40-4a2b-abed-97ce4cf1a732");
user_pref("services.blocklist.addons.checked", 1612279500);
user_pref("services.blocklist.gfx.checked", 1612279500);
user_pref("services.blocklist.pinning.checked", 1612279500);
user_pref("services.blocklist.plugins.checked", 1612279500);
user_pref("services.settings.clock_skew_seconds", -1733);
user_pref("services.settings.last_etag", "\"1612274275163\"");
user_pref("services.settings.last_update_seconds", 1612281590);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1612279500);
user_pref("services.settings.main.cfr-fxa.last_check", 1612279500);
user_pref("services.settings.main.cfr.last_check", 1612279500);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1612279500);
user_pref("services.settings.main.hijack-blocklists.last_check", 1612279500);
user_pref("services.settings.main.language-dictionaries.last_check", 1612279500);
user_pref("services.settings.main.message-groups.last_check", 1612279500);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1612279500);
user_pref("services.settings.main.pioneer-study-addons.last_check", 1612279500);
user_pref("services.settings.main.public-suffix-list.last_check", 1612279500);
user_pref("services.settings.main.search-config.last_check", 1612279500);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1612279500);
user_pref("services.settings.main.sites-classification.last_check", 1612279500);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1612279500);
user_pref("services.settings.main.whats-new-panel.last_check", 1612279500);
user_pref("services.settings.security.onecrl.checked", 1612279500);
user_pref("toolkit.startup.last_success", 1612279339);
user_pref("toolkit.telemetry.cachedClientID", "058820a3-b7ce-4386-8f1b-758c6671f3d6");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
